name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/actions/jekyll-build-pages:v1.0.13
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: _site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
